services:
  db:
    container_name: is_lab_db
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 27062005
    volumes:
      - ./.docker/volumes/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

